version: '3.8'

services:
  t3mt:
    image: 85423296/t3mt:latest
    container_name: t3mt
    restart: unless-stopped
    ports:
      - "8520:80"
    volumes:
      - ./data:/app/backend/data
      - ./logs:/app/backend/logs
      - ./downloads:/app/backend/downloads
    environment:
      - TZ=Asia/Shanghai
