version: '3.8'

services:
  t3mt:
    image: 85423296/t3mt:latest  # 稳定版,使用 latest 或指定版本号如 2.1.4
    container_name: t3mt
    restart: unless-stopped
    ports:
      - "8520:80"
    volumes:
      - ./data:/app/backend/data
      - ./logs:/app/backend/logs
      - ./downloads:/app/backend/downloads
    environment:
      - TZ=Asia/Shanghai
